// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pairwise_distance_vector_cpp
arma::rowvec pairwise_distance_vector_cpp(arma::mat Z, int i);
RcppExport SEXP _dmlpm_pairwise_distance_vector_cpp(SEXP ZSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_distance_vector_cpp(Z, i));
    return rcpp_result_gen;
END_RCPP
}
// log_posterior_it_cpp
double log_posterior_it_cpp(const arma::field<arma::cube>& Y, arma::cube Z, const NumericMatrix& alpha, int i, int t, double sigma2_0, double sigma2_a, double sigma2_z);
RcppExport SEXP _dmlpm_log_posterior_it_cpp(SEXP YSEXP, SEXP ZSEXP, SEXP alphaSEXP, SEXP iSEXP, SEXP tSEXP, SEXP sigma2_0SEXP, SEXP sigma2_aSEXP, SEXP sigma2_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::cube>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_0(sigma2_0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_a(sigma2_aSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_z(sigma2_zSEXP);
    rcpp_result_gen = Rcpp::wrap(log_posterior_it_cpp(Y, Z, alpha, i, t, sigma2_0, sigma2_a, sigma2_z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dmlpm_pairwise_distance_vector_cpp", (DL_FUNC) &_dmlpm_pairwise_distance_vector_cpp, 2},
    {"_dmlpm_log_posterior_it_cpp", (DL_FUNC) &_dmlpm_log_posterior_it_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_dmlpm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
